FileVersion = 1

[Project]
Name = "jsonc-beef"
DefaultNamespace = "jsonc"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\jsonc_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\jsonc.lib"]
