FileVersion = 1

[Project]
Name = "jsonc-beef"
TargetType = "BeefLib"
StartupObject = "jsonc_beef.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\json-c-static.lib"]
